"""Öffentliche API des GenericParser-Pakets."""

from .config import (
    ConfigurationError,
    load_profile,
    load_profiles,
    profile_from_dict,
    profile_to_dict,
    save_profile,
    save_profiles,
)
from .integrations import evercade_profile, snes_pal_profile
from .models import (
    Listing,
    Location,
    MatchDecision,
    MatchResult,
    NormalizedPrice,
    PriceFlag,
    SearchProfile,
)
from .module_api import (
    MODULE_CONTRACT,
    DebugTrace,
    ModuleDebugOptions,
    ModuleListing,
    ModulePageRequest,
    ModulePageResponse,
    ModulePagination,
    ModuleSearchProfile,
    ModuleSummary,
    module_response_from_legacy,
    run_contract_self_tests,
)
from .module_api_v2 import (
    MODULE_CONTRACT_V2,
    V2BatchRequest,
    V2Client,
    V2Criteria,
    V2Filters,
    V2Location,
    V2SearchDefinition,
    V2SingleRequest,
    V2ValidateRequest,
)
from .normalization import compact_text, normalize_text, parse_location, parse_posted_at, parse_price
from .release_identity import VERSION as __version__
from .service import GenericParser, ListingSource
from .sources.kleinanzeigen import (
    FetchedPage,
    KleinanzeigenAdapter,
    KleinanzeigenBlockedError,
    KleinanzeigenHttpClient,
    KleinanzeigenLayoutError,
    KleinanzeigenPageParser,
    KleinanzeigenUrlBuilder,
    LocationVerification,
    PageDiagnostics,
    PageState,
    extract_location_id,
    slugify_keyword,
)

__all__ = [
    "MODULE_CONTRACT",
    "MODULE_CONTRACT_V2",
    "ConfigurationError",
    "DebugTrace",
    "FetchedPage",
    "GenericParser",
    "KleinanzeigenAdapter",
    "KleinanzeigenBlockedError",
    "KleinanzeigenHttpClient",
    "KleinanzeigenLayoutError",
    "KleinanzeigenPageParser",
    "KleinanzeigenUrlBuilder",
    "Listing",
    "ListingSource",
    "Location",
    "LocationVerification",
    "MatchDecision",
    "MatchResult",
    "ModuleDebugOptions",
    "ModuleListing",
    "ModulePageRequest",
    "ModulePageResponse",
    "ModulePagination",
    "ModuleSearchProfile",
    "ModuleSummary",
    "NormalizedPrice",
    "PageDiagnostics",
    "PageState",
    "PriceFlag",
    "SearchProfile",
    "V2BatchRequest",
    "V2Client",
    "V2Criteria",
    "V2Filters",
    "V2Location",
    "V2SearchDefinition",
    "V2SingleRequest",
    "V2ValidateRequest",
    "__version__",
    "compact_text",
    "evercade_profile",
    "extract_location_id",
    "load_profile",
    "load_profiles",
    "module_response_from_legacy",
    "normalize_text",
    "parse_location",
    "parse_posted_at",
    "parse_price",
    "profile_from_dict",
    "profile_to_dict",
    "run_contract_self_tests",
    "save_profile",
    "save_profiles",
    "slugify_keyword",
    "snes_pal_profile",
]
