"""Shared deployment identity for GenericParser 0.43.6."""
VERSION = "0.43.6"
BUILD_ID = "gp-0436-20260803-1"
API_CONTRACT = "match-v6.8-robust-title-worker"
ENTRYPOINT = "generic_parser.cloudflare_worker:Default.fetch"
BOOTSTRAP_MODULE = "generic_parser.cloudflare_v0436"
SEARCH_MODULE = "generic_parser.search_service_v0436"
WORKER_UNIT = "stable-ui+free-cpu+source-next-link+robust-title-fallback"
