"""Shared deployment identity for GenericParser 0.43.4."""
VERSION = "0.43.4"
BUILD_ID = "gp-0434-20260803-1"
API_CONTRACT = "match-v6.6-coverage-evidence-worker"
ENTRYPOINT = "generic_parser.cloudflare_worker:Default.fetch"
BOOTSTRAP_MODULE = "generic_parser.cloudflare_v0434"
SEARCH_MODULE = "generic_parser.search_service_v0434"
WORKER_UNIT = "stable-ui+free-cpu+source-next-link+coverage-evidence"
