"""Shared deployment identity for GenericParser 0.44.2."""
VERSION = "0.44.2"
BUILD_ID = "gp-0442-20260803-1"
API_CONTRACT = "match-v6.9.2-technical-rollback-worker"
ENTRYPOINT = "generic_parser.cloudflare_worker:Default.fetch"
BOOTSTRAP_MODULE = "generic_parser.cloudflare_v0442"
SEARCH_MODULE = "generic_parser.search_service_v0442"
WORKER_UNIT = "technical-base-04363+semantic-cards+safe-css"
