"""Shared deployment identity for GenericParser 0.43.3."""
VERSION = "0.43.3"
BUILD_ID = "gp-0433-20260803-1"
API_CONTRACT = "match-v6.5-stable-ui-worker"
ENTRYPOINT = "generic_parser.cloudflare_worker:Default.fetch"
BOOTSTRAP_MODULE = "generic_parser.cloudflare_v0433"
SEARCH_MODULE = "generic_parser.search_service_v0433"
WORKER_UNIT = "stable-0429-controller+free-cpu+source-next-link"
